# Generated by Django 3.0.8 on 2020-09-12 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerinvoice',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app3.Product'),
            preserve_default=False,
        ),
    ]
